language: node_js
node_js:
  - "stable"
notifications:
  email: false
  
services:
  - postgresql

install:
  - npm install

before_script:
  - psql -c "CREATE USER gitstart WITH PASSWORD 'gitstart';" -U postgres

env:
  global:
  - NODE_ENV=test

before_script:
  - npm add sequelize-cli

script:
  - npm test
after_success: npm run coverage
