language: node_js
node_js:
  - "stable"
notifications:
  email: false
  
services:
  - postgresql

install:
  - npm install

before_script:
  - psql -c "CREATE USER gitstart WITH PASSWORD 'gitstart';" -U postgres

development:
  adapter: postgresql
  encoding: utf8
  database: gitstart_development
  username: gitstart
  password:
  template: template0

env:
  global:
  - NODE_ENV=test

before_script:
  - npm add sequelize-cli

script:
  - npm test
after_success: npm run coverage
