language: node_js
node_js:
  - "stable"
notifications:
  email: false

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432

services:
  - postgresql

install:
  - npm install

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml
  - npm add sequelize-cli

script:
  - npm test
after_success: npm run coverage
